trigger:
- main

pool:
  name: Default  # or the name of the pool you configured

steps:
- checkout: self 
  displayName: 'Checkout Repo'

- script: |
    git config --global user.name "vikaluk"
    git config --global user.email "vikaluk@gmail.com"
  displayName: 'Configure Git user'

- script: |
    cd new-project-playwright
    npm install
    npx playwright install
    npx playwright test --reporter=html
  displayName: 'Execute Playwright'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/new-project-playwright/playwright-report'
    ArtifactName: 'playwright-report'
    publishLocation: 'Container'
  displayName: 'Publish Playwright HTML report artifact'
